# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-21 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=60)),
                ('image_description', models.TextField()),
                ('image', models.ImageField(upload_to='imgs/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Location')),
            ],
            options={
                'ordering': ['image_name'],
            },
        ),
    ]
